title: Caitlin Lienkaemper # your name (or website title) here
logo: "/images/newer_web_photo.png?raw=true"  # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Center for Systems Neuroscience postdocoral fellow at Boston University 
  <br><br>
  Working in Department of Mathematics and Statistics with Gabriel Ocker 
  <br><br>
  <a href="https://scholar.google.com/citations?user=7d3VVVsAAAAJ&hl=en">Google Scholar</a> 
  Email: <a href="mailto:clienk@bu.edu">
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
